sudo: required
services:
  - docker

before_install:
  - docker build -t simoneko/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true simoneko/react-test npm test -- --coverage

after_success:
  - docker build -t simoneko/multi-client ./client
  - docker build -t simoneko/multi-nginx ./nginx
  - docker build -t simoneko/multi-server ./server
  - docker build -t simoneko/multi-worker ./worker  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push simoneko/multi-client 
  - docker push simoneko/multi-nginx 
  - docker push simoneko/multi-server 
  - docker push simoneko/multi-worker